### GET request to example server
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "MyName21",
  "email": "myName21@example.com",
  "address": "123 street",
  "dateOfBirth": "2000-12-12",
  "registeredDate": "2026-02-14"
}
###